# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-14 05:42
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_payments', '0004_paymentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='feedback',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
