# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_payments', '0007_auto_20200429_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Total'),
        ),
    ]
