# Generated by Django 6.0.3 on 2026-03-31 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "codenerix_payments",
            "0018_alter_currency_options_alter_paymentanswer_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreturn",
            name="return_order",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(78364164096),
                ],
                verbose_name="Return Order Number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentreturn",
            name="return_order_ref",
            field=models.CharField(
                default="0",
                max_length=8,
                verbose_name="Return Order Reference",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentreturn",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
