# Generated by Django 6.0.3 on 2026-04-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codenerix_payments", "0019_paymentreturn_return_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentreturn",
            name="ref",
        ),
    ]
