# Generated by Django 5.2.13 on 2026-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codenerix_payments", "0020_remove_paymentreturn_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreturn",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
